# Generated by Django 3.0.5 on 2020-04-16 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pizza', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='tipo',
            field=models.CharField(choices=[('1', 'Lojista'), ('2', 'Consumidor')], max_length=1, verbose_name='Iluminação'),
        ),
    ]
