# Generated by Django 3.0.5 on 2020-04-16 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pizza', '0002_auto_20200416_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='tipo',
            field=models.CharField(choices=[('1', 'Lojista'), ('Consu', 'Consumidor')], max_length=10, verbose_name='Iluminação'),
        ),
    ]
