# Generated by Django 3.0.5 on 2020-05-04 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pizza', '0005_auto_20200419_1312'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cadlojista',
            old_name='nome_Fantasia',
            new_name='nome',
        ),
        migrations.AddField(
            model_name='cadlojista',
            name='nomePizzaria',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
