# Generated by Django 3.0.5 on 2020-05-04 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pizza', '0006_auto_20200504_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadlojista',
            name='diaFuncional',
            field=models.CharField(max_length=100, verbose_name='Dias de Funcinamento'),
        ),
        migrations.AlterField(
            model_name='cadlojista',
            name='horaFinal',
            field=models.CharField(max_length=5, verbose_name='Horário de Fechamento'),
        ),
        migrations.AlterField(
            model_name='cadlojista',
            name='horaInicio',
            field=models.CharField(max_length=5, verbose_name='Hora de Início'),
        ),
        migrations.AlterField(
            model_name='cadlojista',
            name='nomePizzaria',
            field=models.CharField(max_length=50, verbose_name='Nome da Pizzaria'),
        ),
    ]
