# Generated by Django 3.0.5 on 2020-05-11 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pizza', '0008_massa_pedirpizza_sabores_tamanhopizza'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedirpizza',
            name='id_sabor',
        ),
        migrations.RemoveField(
            model_name='pedirpizza',
            name='id_tamanho',
        ),
        migrations.RemoveField(
            model_name='pedirpizza',
            name='id_tipo',
        ),
        migrations.DeleteModel(
            name='Massa',
        ),
        migrations.DeleteModel(
            name='PedirPizza',
        ),
        migrations.DeleteModel(
            name='Sabores',
        ),
        migrations.DeleteModel(
            name='TamanhoPizza',
        ),
    ]
