# Generated by Django 3.0.5 on 2020-05-18 13:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Pizza', '0010_auto_20200518_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadconsumidor',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cadlojista',
            name='nomePizzaria',
            field=models.CharField(max_length=50, verbose_name='Nome da Pizzaria!'),
        ),
    ]
