# Generated by Django 3.0.5 on 2020-05-18 13:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Pizza', '0011_auto_20200518_1022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cadlojista',
            name='author',
        ),
        migrations.AddField(
            model_name='cadlojista',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
