# Generated by Django 3.0.5 on 2020-05-11 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Massa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=30, verbose_name='Tipo de Massa')),
            ],
        ),
        migrations.CreateModel(
            name='Sabores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
                ('ingredientes', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='TamanhoPizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tamanho', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='PedirPizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_sabor', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='menu.Sabores')),
                ('id_tamanho', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='menu.TamanhoPizza')),
                ('id_tipo', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='menu.Massa')),
            ],
        ),
    ]
