# Generated by Django 3.0.5 on 2020-05-12 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sabores',
            name='nome',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
